# @name login
# @prompt cardnumber
# @prompt pin
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
  "cardnumber": "{{cardnumber}}",
  "pin": "{{pin}}"
}

###
@token = {{login.response.body.token}}

### Get all customers
GET http://localhost:3000/customer HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}


### Get card by ID
# @prompt cardid
GET http://localhost:3000/card/bycardnumber/{{cardid}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}


### Uuden kortin luonti
# @prompt cardnumber
# @prompt pin
# @prompt idcustomer
POST http://localhost:3000/card HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "cardnumber": "{{cardnumber}}",
  "pin": "{{pin}}",
  "idcustomer": "{{idcustomer}}",
  "type": "credit/debit"
}

### Uuden käyttäjän luonti
# @prompt cardnumber
# @prompt pin
# @prompt idcustomer
POST http://localhost:3000/card HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "cardnumber": "{{cardnumber}}",
  "pin": "{{pin}}",
  "idcustomer": "{{idcustomer}}",
  "type": "credit/debit"
}


### Update card. Requires admin priviledges
GET http://localhost:3000/card HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}


### Update card. Requires admin priviledges
# @prompt cardid
# @prompt cardnumber
# @prompt pin
# @prompt idcustomer
# @prompt type
PUT http://localhost:3000/card/{{cardid}} HTTP/1.1
Content-Type: application/json
Authorization: bearer {{token}}

{
  "cardnumber": "{{cardnumber}}",
  "pin": "{{pin}}",
  "idcustomer": "{{idcustomer}}",
  "type": "{{type}}"
}

