# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "main", "ci/cd" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: riihimaatti-webapp    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './backend'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use
  # You forced me to do this.
  AZURE_WEBAPP_PUBLISH_PROFILE: <publishData><publishProfile profileName="riihimaatti - Web Deploy" publishMethod="MSDeploy" publishUrl="riihimaatti.scm.azurewebsites.net:443" msdeploySite="riihimaatti" userName="$riihimaatti" userPWD="LjvaaqqFxdcTN9jdyafowSTfNSCMTDsJ9hgz2W1jydZmhxLamPx3xFtBxbu5" destinationAppUrl="https://riihimaatti.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="riihimaatti - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-db3-183.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="riihimaatti\$riihimaatti" userPWD="LjvaaqqFxdcTN9jdyafowSTfNSCMTDsJ9hgz2W1jydZmhxLamPx3xFtBxbu5" destinationAppUrl="https://riihimaatti.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="riihimaatti - Zip Deploy" publishMethod="ZipDeploy" publishUrl="riihimaatti.scm.azurewebsites.net:443" userName="$riihimaatti" userPWD="LjvaaqqFxdcTN9jdyafowSTfNSCMTDsJ9hgz2W1jydZmhxLamPx3xFtBxbu5" destinationAppUrl="https://riihimaatti.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      working-directory: ./backend
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
